### PR TITLE
Bring first code snippet examples into dev

### PR DESCRIPTION
**Pull request by tariqshihadah**
Just to get us started, I think it would be helpful to pull in the first example or two that we have available into the `dev` branch. @phildias if there are any other low-hanging fruit examples that you'd like to include in this first PR, let me know and we can get those added in before merging.

### CODE REVIEW

**Comment by tariqshihadah** [comment]
@ribpy89 This could be a good spot for you to plug in to do a quick review of the added examples if you have a moment!

**Comment by phildias** [comment]
There are two more I was working on. I have the code for it all, but I just need to add the comments - they're "line geom to mile markers" and "line mile markers to geom" cases.

**Comment by tariqshihadah** [comment]
> There are two more I was working on. I have the code for it all, but I just need to add the comments - they're "line geom to mile markers" and "line mile markers to geom" cases.

Those sound *chef's kiss*, thanks Felipe! We can hold off on this merge until those are in.

**Comment by phildias** [comment]
There, I finally added the two new snippets I wanted! 

This now has a green light from me! @tariqshihadah, you might want to go over the two new files and make sure there's nothing odd in them.

**Comment by tariqshihadah** [comment]
Thanks @phildias ! Finally getting around to pushing this to dev in prep for a new version release.

**Comment by phildias** [comment]
Woop woop!!!! Awesome, happy to see it merged!!!

**Pull request merged**
